name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
      branches: 
      - "*"

jobs:
  build:
    strategy:
      matrix:
        ubuntu: ['12.04','14.04','16.04','18.04','20.04','22.04']
    runs-on: ubuntu-latest
    env:
      IMG_NAME: aptible/ubuntu

    steps:

    - uses: actions/checkout@v4
    
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Make Build
      run: make build

    - name: Run Tests
      run: make test